-- CreateTable
CREATE TABLE "Sex" (
    "Sex_ID" SERIAL NOT NULL,
    "User_ID" INTEGER NOT NULL,
    "Body_Sex" INTEGER NOT NULL,
    "Heart_Sex" INTEGER NOT NULL,
    "Like_Sex" INTEGER NOT NULL,

    CONSTRAINT "Sex_pkey" PRIMARY KEY ("Sex_ID")
);

-- AddForeignKey
ALTER TABLE "Sex" ADD CONSTRAINT "Sex_User_ID_fkey" FOREIGN KEY ("User_ID") REFERENCES "EqualUser"("User_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
